### ISSUE TITLE
Doesnt work on Android 10

### ISSUE THREAD

**Issue by Clouraxe** [timawesomeness/PairWiimote#1]
App doesnt work, pressing 1 & 2 blinks and then asks for a passcode, inputting 0000 or 1234 sometimes fails, but sometimes "connects" but the wiimote stays blinking indefinitely.

OS: Android 10 (Havoc ROM)
Phone: Xiaomi redmi note 4x

Ill gladly provide more details if needed

**Comment by timawesomeness** [comment]
That is an issue with your device's Bluetooth stack and there's unfortunately nothing this app can do about it. Wii remotes do not appear to be compatible with all manufacturers' devices, and Xiaomi is one of those that has a non-standard Bluetooth implementation.
