### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [timawesomeness/PairWiimote#3]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by timawesomeness** [comment]
I don't want to do it myself, but if someone wants to do it for me I would be happy to support that.

**Comment by Poussinou** [comment]
Here you go with the Request For Packaging:
* https://gitlab.com/fdroid/rfp/-/issues/1469

**Comment by IzzySoft** [comment]
F-Droid maintainer here. Could you please establish [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo here (for descriptions, screenshots etc – details behind the link)? You know: "a picture tells more than 1.000 words", and all that :wink: You can also use that to deploy to other places, eg Play Store is definitely supported – so maintain them once, deploy many.

Thanks in advance!

**Comment by IzzySoft** [comment]
@timawesomeness any chance to get Fastlane established (at least `short_description.txt` and `full_description.txt` for `en-US`) so we can process the RFP?
